# CI workflow to build and test

name: CI Build & Test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
      - uses: ./
      - name: Check MASM Path
        run: |
          $ml64Path = Get-Command ml64.exe -ErrorAction SilentlyContinue
          if ($ml64Path) {
            Write-Output "ml64.exe found in PATH: $($ml64Path.Source)"
          } else {
            Write-Error "ml64.exe not found in PATH."
            exit 1
          }
