# CI workflow to build and test

name: CI Build & Test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: ${{matrix.platform}}
      - uses: ./
        with:
          vs-architecture: ${{matrix.platform}}
      - name: Check MASM ${{matrix.platform}} Path
        run: |
          if ("${{matrix.platform}}" -eq "x64") {
            $ml64Path = Get-Command ml64.exe -ErrorAction SilentlyContinue
            if ($ml64Path) {
              Write-Output "ml64.exe found in PATH: $($ml64Path.Source)"
            } else {
              Write-Error "ml64.exe not found in PATH."
              exit 1
            }
          } elseif ("${{matrix.platform}}" -eq "x86") {
            $mlPath = Get-Command ml.exe -ErrorAction SilentlyContinue
            if ($mlPath) {
              Write-Output "ml.exe found in PATH: $($mlPath.Source)"
            } else {
              Write-Error "ml.exe not found in PATH."
              exit 1
            }
          } else {
            Write-Error "Unknown platform ${{matrix.platform}} to get ml<XXX>.exe in PATH."
            exit 1
          }

