# CI workflow to build and test

name: CI Build & Test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
      - uses: ./
      - name: Check MASM Path
        run: |
          if (Test-Path env:masmPath) {
            Write-Output "MASM path is set to: $env:masmPath"
            if (Test-Path "$env:masmPath\ml64.exe") {
              Write-Output "ml64.exe found at the specified path."
            } else {
              Write-Error "ml64.exe not found at the specified path."
              exit 1
            }
          } else {
            Write-Error "MASM path environment variable is not set."
            exit 1
          }
